### ISSUE TITLE
Error no corresponding build

### ISSUE THREAD

**Issue by willforsyth** [mllrsohn/grunt-node-webkit-builder#133]
Hi,

I am trying to run the example using grunt nodewebkit and getting this error.

ERROR: The version 0.10.0 does not have a corresponding build posted at http://dl.node-webkit.org/. Please choose a version from that list.
Fatal error: Unable to download nodewebkit.

I have tried other versions and getting the same error.

**Comment by sjlynch** [comment]
I'm getting this as well. What was your solution?
