### ISSUE TITLE
Unable to download nodewebkit

### ISSUE THREAD

**Issue by estvmachine** [mllrsohn/grunt-node-webkit-builder#136]
With my code already i did a nodewebkit version with **'node-webkit-v0.8.6-win-ia32'** ([download page node-webkit](https://github.com/nwjs/nw.js/blob/757cfcb1ebdec803fec30059e3b9ff189d1847c7/README.md) ) because my app works in **Node v0.10.x**, now i want to do that with grunt but the task try to download the last version and additionally fails.

![image](https://cloud.githubusercontent.com/assets/2062668/7867770/f3691426-0545-11e5-91e7-9f9755d4c2ab.png)

My code:

gruntfile.js
```javascript
grunt.initConfig({
   nodewebkit: {
	    options: {
	        platforms: ['win'],
	        buildDir: './webkitbuilds', // Where the build version of my node-webkit app is saved
	    },
	    src: ['./dest/**/*'] // Your node-webkit app
	  }
});
```

The package.json

```javascript
{
  "name": "webrandomprod",
  "main": "index.html",
  "node-main": "server.js",
  "description": "A MEAN application for module of Production of RANDOM ERP",
  "version": "0.0.1",
  "author": "Stevmachine",
  "engines": {
    "node": "0.10.x",
    "npm": "1.4.x"
  },
  "window": {
    "title": "node-webkit demo",
    "icon": "link.png",
    "toolbar": true,
    "frame": false,
    "width": 800,
    "height": 500,
    "position": "mouse",
    "min_width": 400,
    "min_height": 200,
    "max_width": 800,
    "max_height": 600
  },
  "webkit": {
    "plugin": true
  }
}
```

**Comment by d11e9** [comment]
:+1: me too

**Comment by adam-lynch** [comment]
Thanks for reporting... We'll track this bug at https://github.com/mllrsohn/node-webkit-builder/issues/222
